apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging-helm
  namespace: flux-system
spec:
  interval: 1m
  path: "./new"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m
