apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 9.3.7 # Optional: You can omit to get latest
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
