apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 20.1.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
