apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "9.3.5"           # You can pick latest or specify a stable version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    service:
      type: LoadBalancer       # To expose it externally
